version: '3'
services:
  app:
    build: .
    ports:
      - '4040:4000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./start.sh"]
  db:
    image: mysql:8.0.21
    container_name: godockerDB # 追加
    ports:
      - '4406:4406'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - go_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'go_mysql8_development'
volumes:
  go_mysql_data: